# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casename', models.CharField(max_length=50, verbose_name='\u7528\u4f8b\u540d\u79f0')),
                ('creatdata', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('lastmodif', models.DateField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4')),
                ('remark', models.CharField(max_length=50, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulesname', models.CharField(max_length=50, verbose_name='\u6a21\u5757\u540d\u79f0')),
                ('promodules', models.CharField(max_length=50, verbose_name='\u524d\u7f6e\u6a21\u5757')),
                ('creatdata', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('lastmodif', models.DateField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4')),
                ('remark', models.CharField(max_length=50, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='TestUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=20)),
                ('creatdata', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('lastmodif', models.DateField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.AddField(
            model_name='modules',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.TestUsers'),
        ),
        migrations.AddField(
            model_name='cases',
            name='mname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Modules'),
        ),
    ]
