# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testusers',
            name='password',
            field=models.CharField(max_length=20, verbose_name='\u5bc6\u7801'),
        ),
    ]
