# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_auto_20170829_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Param1', models.CharField(max_length=50, verbose_name='\u53c2\u65701')),
                ('Param2', models.CharField(max_length=50, verbose_name='\u53c2\u65702')),
            ],
        ),
        migrations.AddField(
            model_name='testusers',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cases',
            name='mname',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auto.Modules', verbose_name='\u6240\u5c5e\u6a21\u5757'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='remark',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='promodules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Modules', verbose_name='\u524d\u7f6e\u6a21\u5757'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='cname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Cases', verbose_name='\u6d4b\u8bd5\u7528\u4f8b'),
        ),
    ]
